// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { DbVector2 as __DbVector2 } from "./db_vector_2_type";

export type Enemy = {
  enemyId: number,
  routeId: number,
  enemyType: string,
  position: __DbVector2,
  currentHp: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Enemy {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("enemyId", AlgebraicType.createU32Type()),
      new ProductTypeElement("routeId", AlgebraicType.createU32Type()),
      new ProductTypeElement("enemyType", AlgebraicType.createStringType()),
      new ProductTypeElement("position", __DbVector2.getTypeScriptAlgebraicType()),
      new ProductTypeElement("currentHp", AlgebraicType.createF32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Enemy): void {
    Enemy.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Enemy {
    return Enemy.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


