// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
export type EnemyConfig = {
  enemyType: string,
  maxHp: number,
  level: number,
  behavior: string,
  baseExpReward: number,
  movementSpeed: number,
  damage: number,
  attackRange: number,
  aggroRange: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace EnemyConfig {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("enemyType", AlgebraicType.createStringType()),
      new ProductTypeElement("maxHp", AlgebraicType.createF32Type()),
      new ProductTypeElement("level", AlgebraicType.createU32Type()),
      new ProductTypeElement("behavior", AlgebraicType.createStringType()),
      new ProductTypeElement("baseExpReward", AlgebraicType.createU32Type()),
      new ProductTypeElement("movementSpeed", AlgebraicType.createU32Type()),
      new ProductTypeElement("damage", AlgebraicType.createU32Type()),
      new ProductTypeElement("attackRange", AlgebraicType.createU32Type()),
      new ProductTypeElement("aggroRange", AlgebraicType.createU32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: EnemyConfig): void {
    EnemyConfig.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): EnemyConfig {
    return EnemyConfig.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


