// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { AiBehavior as __AiBehavior } from "./ai_behavior_type";

export type Enemy = {
  name: string,
  level: number,
  expReward: number,
  health: number,
  moveSpeed: number,
  damage: number,
  aiBehavior: __AiBehavior,
  attackRange: number,
  aggroRange: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Enemy {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("name", AlgebraicType.createStringType()),
      new ProductTypeElement("level", AlgebraicType.createU32Type()),
      new ProductTypeElement("expReward", AlgebraicType.createU32Type()),
      new ProductTypeElement("health", AlgebraicType.createF32Type()),
      new ProductTypeElement("moveSpeed", AlgebraicType.createF32Type()),
      new ProductTypeElement("damage", AlgebraicType.createF32Type()),
      new ProductTypeElement("aiBehavior", __AiBehavior.getTypeScriptAlgebraicType()),
      new ProductTypeElement("attackRange", AlgebraicType.createF32Type()),
      new ProductTypeElement("aggroRange", AlgebraicType.createF32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Enemy): void {
    Enemy.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Enemy {
    return Enemy.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


