// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { Job } from "./job_type";
import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `Job`.
 *
 * Obtain a handle from the [`job`] property on [`RemoteTables`],
 * like `ctx.db.job`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.job.on_insert(...)`.
 */
export class JobTableHandle {
  tableCache: TableCache<Job>;

  constructor(tableCache: TableCache<Job>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<Job> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `jobId` unique index on the table `Job`,
   * which allows point queries on the field of the same name
   * via the [`JobJobIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.job.jobId().find(...)`.
   *
   * Get a handle on the `jobId` unique index on the table `Job`.
   */
  jobId = {
    // Find the subscribed row whose `jobId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): Job | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.jobId, col_val)) {
          return row;
        }
      }
    },
  };
  /**
   * Access to the `jobKey` unique index on the table `Job`,
   * which allows point queries on the field of the same name
   * via the [`JobJobKeyUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.job.jobKey().find(...)`.
   *
   * Get a handle on the `jobKey` unique index on the table `Job`.
   */
  jobKey = {
    // Find the subscribed row whose `jobKey` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: string): Job | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.jobKey, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: Job) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: Job) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: Job) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: Job) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: Job, newRow: Job) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: Job, newRow: Job) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
