// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { FacingDirection as __FacingDirection } from "./facing_direction_type";
import { PlayerState as __PlayerState } from "./player_state_type";

export type Player = {
  identity: Identity,
  playerId: number,
  name: string,
  x: number,
  y: number,
  state: __PlayerState,
  facing: __FacingDirection,
  lastActive: Timestamp,
  currentHp: number,
  maxHp: number,
  currentMana: number,
  maxMana: number,
  level: number,
  experience: number,
  isTyping: boolean,
  job: string,
  inCombat: boolean,
  lastCombatTime: Timestamp,
  isOnline: boolean,
  banStatus: boolean,
  deathX: number,
  deathY: number,
  respawnAvailableAt: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Player {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("identity", AlgebraicType.createIdentityType()),
      new ProductTypeElement("playerId", AlgebraicType.createU32Type()),
      new ProductTypeElement("name", AlgebraicType.createStringType()),
      new ProductTypeElement("x", AlgebraicType.createF32Type()),
      new ProductTypeElement("y", AlgebraicType.createF32Type()),
      new ProductTypeElement("state", __PlayerState.getTypeScriptAlgebraicType()),
      new ProductTypeElement("facing", __FacingDirection.getTypeScriptAlgebraicType()),
      new ProductTypeElement("lastActive", AlgebraicType.createTimestampType()),
      new ProductTypeElement("currentHp", AlgebraicType.createF32Type()),
      new ProductTypeElement("maxHp", AlgebraicType.createF32Type()),
      new ProductTypeElement("currentMana", AlgebraicType.createF32Type()),
      new ProductTypeElement("maxMana", AlgebraicType.createF32Type()),
      new ProductTypeElement("level", AlgebraicType.createU32Type()),
      new ProductTypeElement("experience", AlgebraicType.createU32Type()),
      new ProductTypeElement("isTyping", AlgebraicType.createBoolType()),
      new ProductTypeElement("job", AlgebraicType.createStringType()),
      new ProductTypeElement("inCombat", AlgebraicType.createBoolType()),
      new ProductTypeElement("lastCombatTime", AlgebraicType.createTimestampType()),
      new ProductTypeElement("isOnline", AlgebraicType.createBoolType()),
      new ProductTypeElement("banStatus", AlgebraicType.createBoolType()),
      new ProductTypeElement("deathX", AlgebraicType.createF32Type()),
      new ProductTypeElement("deathY", AlgebraicType.createF32Type()),
      new ProductTypeElement("respawnAvailableAt", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Player): void {
    Player.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Player {
    return Player.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


