// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { DamageType as __DamageType } from "./damage_type_type";

export type PlayerDamageEvent = {
  damageEventId: number,
  playerIdentity: Identity,
  spawnId: number,
  damageAmount: number,
  damageType: __DamageType,
  projectile: string | undefined,
  skillEffect: string | undefined,
  timestamp: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace PlayerDamageEvent {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("damageEventId", AlgebraicType.createU32Type()),
      new ProductTypeElement("playerIdentity", AlgebraicType.createIdentityType()),
      new ProductTypeElement("spawnId", AlgebraicType.createU32Type()),
      new ProductTypeElement("damageAmount", AlgebraicType.createF32Type()),
      new ProductTypeElement("damageType", __DamageType.getTypeScriptAlgebraicType()),
      new ProductTypeElement("projectile", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("skillEffect", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("timestamp", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: PlayerDamageEvent): void {
    PlayerDamageEvent.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): PlayerDamageEvent {
    return PlayerDamageEvent.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


