// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { DbRect as __DbRect } from "./db_rect_type";

export type SpawnRoute = {
  routeId: number,
  enemy: string,
  spawnArea: __DbRect,
  maxEnemies: number,
  spawnInterval: number,
  lastSpawnTime: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace SpawnRoute {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("routeId", AlgebraicType.createU32Type()),
      new ProductTypeElement("enemy", AlgebraicType.createStringType()),
      new ProductTypeElement("spawnArea", __DbRect.getTypeScriptAlgebraicType()),
      new ProductTypeElement("maxEnemies", AlgebraicType.createU8Type()),
      new ProductTypeElement("spawnInterval", AlgebraicType.createU32Type()),
      new ProductTypeElement("lastSpawnTime", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: SpawnRoute): void {
    SpawnRoute.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): SpawnRoute {
    return SpawnRoute.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


