import type { ClassConfig } from '@/player/combat/attack-types';

export const classAttributes: Record<string, ClassConfig> = {
  soldier: {
    displayName: 'Soldier',
    spriteKey: 'soldier',
    baseStats: {
      health: 100,
      moveSpeed: 160,
    },
    attacks: {
      attack1: {
        attackType: 'standard',
        name: 'Quick Strike',
        damage: 10,
        cooldown: 300,
        critChance: 0.15,
        knockback: 5,
        range: 0,
        hits: 1,
      },
      attack2: {
        attackType: 'standard',
        name: 'Power Slash',
        damage: 18,
        cooldown: 600,
        critChance: 0.25,
        knockback: 10,
        range: 0,
        hits: 1,
      },
      attack3: {
        attackType: 'standard',
        name: 'Combo Attack',
        damage: 15,
        cooldown: 450,
        critChance: 0.2,
        knockback: 8,
        range: 0,
        hits: 3,
      },
    },
  },
  knight: {
    displayName: 'Knight',
    spriteKey: 'knight',
    baseStats: {
      health: 150,
      moveSpeed: 140,
    },
    attacks: {
      attack1: {
        attackType: 'standard',
        name: 'Sword Slash',
        damage: 12,
        cooldown: 350,
        critChance: 0.1,
        knockback: 5,
        range: 50,
        hits: 1,
      },
      attack2: {
        attackType: 'standard',
        name: 'Shield Bash',
        damage: 15,
        cooldown: 500,
        critChance: 0.05,
        knockback: 20,
        range: 40,
        hits: 1,
      },
      attack3: {
        attackType: 'standard',
        name: 'Heavy Cleave',
        damage: 25,
        cooldown: 800,
        critChance: 0.15,
        knockback: 15,
        range: 65,
        hits: 1,
      },
    },
  },
  wizard: {
    displayName: 'Wizard',
    spriteKey: 'wizard',
    baseStats: {
      health: 80,
      moveSpeed: 150,
      mana: 100,
    },
    attacks: {
      attack1: {
        attackType: 'projectile',
        name: 'Magic Missile',
        damage: 12,
        cooldown: 400,
        critChance: 0.2,
        knockback: 3,
        range: 400,
        hits: 1,
        projectileSpeed: 300,
        projectileSize: 10,
        projectileSprite: 'magicMissile',
      },
      attack2: {
        attackType: 'area',
        name: 'Arcane Blast',
        damage: 20,
        cooldown: 800,
        critChance: 0.25,
        knockback: 10,
        range: 80,
        hits: 1,
        radius: 80,
        effectSprite: 'arcaneBlast',
      },
      attack3: {
        attackType: 'area',
        name: 'Meteor Strike',
        damage: 30,
        cooldown: 1200,
        critChance: 0.1,
        knockback: 15,
        range: 120,
        hits: 3,
        radius: 120,
        effectSprite: 'meteorStrike',
      },
    },
  },
};

// Export a default object for compatibility with existing imports
export default { classes: classAttributes };
