import type { JobConfig } from '@/player/combat/attack-types';

// Shared attack configuration for all jobs
const sharedAttacks = {
  attack1: {
    attackType: 'standard' as const,
    name: 'Quick Strike',
    description:
      'A swift blade attack that deals moderate damage to nearby enemies. Low cooldown allows for rapid strikes.',
    damage: 10,
    cooldown: 0.5,
    critChance: 0,
    knockback: 500,
    range: 50,
    hits: 1,
    targets: 5,
    modifiers: ['sword' as const],
    manaCost: 0,
    ammoCost: 0,
    manaLeech: 3, // Default mana leech for basic attack
    icon: 'heal1',
    audio: 'p_att_phys',
  },
  attack2: {
    attackType: 'standard' as const,
    name: 'Power Slash',
    description:
      'A devastating overhead swing that cleaves through multiple foes. Deals heavy damage with minimal knockback.A devastating overhead swing that cleaves through multiple foes. Deals heavy damage with minimal knockback.A devastating overhead swing that cleaves through multiple foes. Deals heavy damage with minimal knockback.A devastating overhead swing that cleaves through multiple foes. Deals heavy damage with minimal knockback.',
    damage: 50,
    cooldown: 0.5,
    critChance: 0,
    knockback: 10,
    range: 75,
    hits: 1,
    targets: 6,
    modifiers: ['sword' as const],
    manaCost: 0,
    ammoCost: 0,
    icon: 'heal1',
    audio: 'p_att_phys',
  },
  attack3: {
    attackType: 'standard' as const,
    name: 'Combo Attack',
    description: 'A ranged attack.',
    damage: 15,
    cooldown: 0.5,
    critChance: 1,
    knockback: 0,
    range: 500,
    hits: 1,
    targets: 1,
    modifiers: ['bow' as const],
    manaCost: 10,
    ammoCost: 0,
    icon: 'heal1',
    audio: 'p_att_phys',
  },
};

export const jobAttributes: Record<string, JobConfig> = {
  soldier: {
    displayName: 'Soldier',
    spriteKey: 'soldier',
    unlockLevel: 0, // Unlocked by default
    baseStats: {
      health: 100,
      moveSpeed: 160,
      mana: 30,
      hpRecovery: 1,
      manaRecovery: 0.5,
      resistances: {
        sword: 5,
        axe: 0,
        bow: -5,
        spear: -5,
        dark: 0,
        spike: -5,
        claw: -10,
        greatsword: 10,
      },
    },
    attacks: {
      attack1: {
        attackType: 'standard' as const,
        name: 'Quick Strike',
        description:
          'A swift blade attack that deals moderate damage to nearby enemies. Low cooldown allows for rapid strikes.',
        damage: 10,
        cooldown: 0.5,
        critChance: 0,
        knockback: 500,
        range: 50,
        hits: 1,
        targets: 5,
        modifiers: ['sword' as const],
        manaCost: 0,
        ammoCost: 0,
        manaLeech: 3, // Moderate mana leech for soldier
        icon: 'heal1',
        audio: 'p_att_phys',
      },
      attack2: {
        attackType: 'standard' as const,
        name: 'Power Slash',
        description:
          'A devastating overhead swing that cleaves through multiple foes. Deals heavy damage with minimal knockback.A devastating overhead swing that cleaves through multiple foes. Deals heavy damage with minimal knockback.A devastating overhead swing that cleaves through multiple foes. Deals heavy damage with minimal knockback.A devastating overhead swing that cleaves through multiple foes. Deals heavy damage with minimal knockback.',
        damage: 50,
        cooldown: 0.5,
        critChance: 0,
        knockback: 10,
        range: 75,
        hits: 1,
        targets: 6,
        modifiers: ['sword' as const],
        manaCost: 10,
        ammoCost: 0,
        icon: 'heal2',
        audio: 'p_att_phys',
      },
      attack3: {
        attackType: 'projectile' as const,
        name: 'Combo Attack',
        description:
          'Unleash a flurry of 3 strikes with high critical chance. Extended range and moderate mana cost.',
        damage: 15,
        cooldown: 0.5,
        critChance: 1,
        knockback: 8,
        range: 500,
        hits: 1,
        targets: 1,
        modifiers: ['sword' as const],
        manaCost: 0,
        ammoCost: 0,
        projectile: 'arrow', // Test projectile for soldier
        icon: 'heal3',
        audio: 'p_att_phys',
      },
    },
    passives: {
      passive1: {
        name: 'Combat Training',
        description:
          'Years of military discipline grant +10% attack speed and +5% damage reduction.',
      },
      passive2: {
        name: 'Combat Training',
        description:
          'Years of military discipline grant +10% attack speed and +5% damage reduction.',
      },
    },
  },
  knight: {
    displayName: 'Knight',
    spriteKey: 'knight',
    unlockLevel: 2, // Unlock at level 5
    baseStats: {
      health: 150,
      moveSpeed: 140,
      mana: 50,
      hpRecovery: 1.5,
      manaRecovery: 0.3,
      resistances: {
        sword: 20,
        axe: 15,
        bow: 5,
        spear: 10,
        dark: 10,
        spike: 15,
        claw: 10,
        greatsword: 25,
      },
    },
    attacks: sharedAttacks,
    passives: {
      passive1: {
        name: 'Shield Wall',
        description:
          'Heavy armor training provides +25% damage reduction and immunity to knockback.',
      },
    },
  },
  wizard: {
    displayName: 'Wizard',
    spriteKey: 'wizard',
    unlockLevel: 0, // Unlock at level 10
    baseStats: {
      health: 80,
      moveSpeed: 150,
      mana: 100,
      hpRecovery: 0.5,
      manaRecovery: 2,
      resistances: {
        sword: -10,
        axe: -10,
        bow: 0,
        spear: -5,
        dark: 20,
        spike: -15,
        claw: -15,
        greatsword: -5,
      },
    },
    attacks: {
      attack1: {
        attackType: 'standard' as const,
        name: 'Frost Bolt',
        description: 'A chilling magical attack that slows enemies.',
        damage: 15,
        cooldown: 0.6,
        critChance: 0.2,
        knockback: 300,
        range: 200,
        hits: 1,
        targets: 3,
        modifiers: ['dark' as const],
        manaCost: 0,
        ammoCost: 0,
        manaLeech: 1, // Low mana leech for wizard, relies on high mana regen
        skillEffect: 'freeze',
        icon: 'heal1',
        audio: 'p_att_phys',
      },
      attack2: {
        attackType: 'area' as const,
        name: 'Holy Nova',
        description: 'Unleashes a radiant explosion that damages all enemies around you.',
        damage: 40,
        cooldown: 0.8,
        critChance: 0.15,
        knockback: 200,
        range: 250,
        radius: 150,
        effectSprite: 'holy',
        hits: 1,
        targets: 8,
        modifiers: ['dark' as const],
        manaCost: 0,
        ammoCost: 0,
        skillEffect: 'holy',
        icon: 'heal1',
        audio: 'p_att_phys',
      },
      attack3: {
        attackType: 'projectile' as const,
        name: 'Arcane Missile',
        description: 'Launch a homing magical projectile that explodes on impact.',
        damage: 25,
        cooldown: 1.0,
        critChance: 0.3,
        knockback: 400,
        range: 400,
        hits: 2,
        targets: 1,
        modifiers: ['dark' as const],
        manaCost: 0,
        ammoCost: 0,
        projectile: 'fireball', // Using arrow as placeholder for magic missile
        // skillEffect: 'holy', // Explosion effect on hit
        icon: 'heal1',
        audio: 'p_att_phys',
      },
    },
    passives: {
      passive1: {
        name: 'Arcane Power',
        description: 'Mystical knowledge grants +50% mana regeneration and +20% spell damage.',
      },
    },
  },
  archer: {
    displayName: 'Archer',
    spriteKey: 'archer',
    unlockLevel: 0, // Unlocked by default
    baseStats: {
      health: 90,
      moveSpeed: 170,
      mana: 40,
      hpRecovery: 0.8,
      manaRecovery: 0.8,
      resistances: {
        sword: -5,
        axe: -5,
        bow: 15,
        spear: 0,
        dark: 5,
        spike: -10,
        claw: -10,
        greatsword: 0,
      },
    },
    attacks: {
      attack1: {
        attackType: 'projectile' as const,
        name: 'Quick Shot',
        description:
          'A swift arrow shot that deals moderate damage at range. Low cooldown for rapid fire.',
        damage: 12,
        cooldown: 0.4,
        critChance: 0.15,
        knockback: 300,
        range: 300,
        hits: 1,
        targets: 1,
        modifiers: ['bow' as const],
        manaCost: 0,
        ammoCost: 0,
        manaLeech: 2, // Low mana leech for ranged combat
        projectile: 'arrow',
        icon: 'heal1',
        audio: 'p_att_phys',
      },
      attack2: {
        attackType: 'projectile' as const,
        name: 'Power Shot',
        description: 'A charged arrow that pierces through enemies dealing heavy damage.',
        damage: 35,
        cooldown: 0.8,
        critChance: 0.25,
        knockback: 600,
        range: 400,
        hits: 1,
        targets: 3,
        modifiers: ['bow' as const],
        manaCost: 0,
        ammoCost: 0,
        projectile: 'arrow',
        icon: 'heal1',
        audio: 'p_att_phys',
      },
      attack3: {
        attackType: 'projectile' as const,
        name: 'Rain of Arrows',
        description: 'Unleash multiple arrows in a wide arc, hitting all enemies in front.',
        damage: 20,
        cooldown: 1.2,
        critChance: 0.1,
        knockback: 200,
        range: 350,
        hits: 3,
        targets: 5,
        modifiers: ['bow' as const],
        manaCost: 0,
        ammoCost: 0,
        projectile: 'arrow',
        icon: 'heal1',
        audio: 'p_att_phys',
      },
    },
    passives: {
      passive1: {
        name: 'Eagle Eye',
        description: 'Keen vision increases attack range by +30% and critical hit chance by +15%.',
      },
    },
  },
  'armored-axeman': {
    displayName: 'Armored Axeman',
    spriteKey: 'armored-axeman',
    unlockLevel: 15, // Unlock at level 15
    baseStats: {
      health: 140,
      moveSpeed: 130,
      mana: 40,
      hpRecovery: 1.2,
      manaRecovery: 0.4,
      resistances: {
        sword: 10,
        axe: 25,
        bow: 0,
        spear: 5,
        dark: 0,
        spike: 10,
        claw: 5,
        greatsword: 20,
      },
    },
    attacks: sharedAttacks,
    passives: {
      passive1: {
        name: 'Heavy Armor',
        description:
          'Reinforced plating grants +20% damage reduction but reduces movement speed by -10%.',
      },
    },
  },
  'knight-templar': {
    displayName: 'Knight Templar',
    spriteKey: 'knight-templar',
    unlockLevel: 20, // Unlock at level 20
    baseStats: {
      health: 160,
      moveSpeed: 135,
      mana: 80,
      hpRecovery: 2,
      manaRecovery: 1,
      resistances: {
        sword: 15,
        axe: 10,
        bow: 10,
        spear: 10,
        dark: -20,
        spike: 15,
        claw: 10,
        greatsword: 20,
      },
    },
    attacks: sharedAttacks,
    passives: {
      passive1: {
        name: 'Divine Protection',
        description:
          'Holy blessing provides +30% resistance to dark magic and +2 HP regeneration per second.',
      },
    },
  },
  lancer: {
    displayName: 'Lancer',
    spriteKey: 'lancer',
    unlockLevel: 0, // Unlocked by default
    baseStats: {
      health: 110,
      moveSpeed: 500, // Really fast movement speed
      mana: 50,
      hpRecovery: 1,
      manaRecovery: 0.7,
      knockbackImmune: true, // Lancer is immune to knockback
      resistances: {
        sword: 5,
        axe: 0,
        bow: -5,
        spear: 20,
        dark: 0,
        spike: -5,
        claw: -5,
        greatsword: 10,
      },
    },
    attacks: {
      attack1: sharedAttacks.attack1,
      attack2: {
        attackType: 'dash' as const,
        description: 'some dash attack.',
        name: 'Piercing Dash',
        damage: 40,
        cooldown: 0.8,
        critChance: 0.15,
        knockback: 15,
        range: 100,
        hits: 1,
        targets: 10,
        modifiers: ['spear' as const],
        manaCost: 0,
        ammoCost: 0,
        dashDistance: 300,
        dashSpeed: 800,
        icon: 'heal1',
        audio: 'p_att_phys',
      },
      attack3: {
        attackType: 'dash' as const,
        name: 'Lightning Thrust',
        description: 'some dash attack.',
        damage: 25,
        cooldown: 1.2,
        critChance: 0.3,
        knockback: 20,
        range: 100,
        hits: 2,
        targets: 10,
        modifiers: ['spear' as const],
        manaCost: 0,
        ammoCost: 0,
        dashDistance: 1000,
        dashSpeed: 1000,
        icon: 'heal',
      },
    },
    passives: {
      passive1: {
        name: 'Reach Advantage',
        description: 'Spear mastery extends attack range by +40% and enables dash attacks.',
      },
      passive2: {
        name: 'Steadfast Stance',
        description: 'Complete immunity to knockback effects, allowing uninterrupted combat.',
      },
    },
  },
  priest: {
    displayName: 'Priest',
    spriteKey: 'priest',
    unlockLevel: 8, // Unlock at level 8
    baseStats: {
      health: 85,
      moveSpeed: 145,
      mana: 120,
      hpRecovery: 1.5,
      manaRecovery: 2.5,
      resistances: {
        sword: -15,
        axe: -15,
        bow: -5,
        spear: -10,
        dark: -30,
        spike: -20,
        claw: -20,
        greatsword: -10,
      },
    },
    attacks: {
      attack1: sharedAttacks.attack1,
      attack2: {
        attackType: 'heal' as const,
        name: 'Heal',
        description: 'Restore health to nearby party members with divine healing power.',
        damage: 50, // Used as heal amount
        cooldown: 2.0,
        critChance: 0,
        knockback: 0,
        range: 200,
        hits: 1,
        targets: 3, // Can heal up to 3 party members
        modifiers: [],
        manaCost: 20,
        ammoCost: 0,
        skillEffect: 'freeze',
        icon: 'heal2',
        audio: 'p_att_heal',
      },
      attack3: sharedAttacks.attack3,
    },
    passives: {
      passive1: {
        name: 'Blessed Recovery',
        description: 'Divine favor grants +100% health regeneration and heals nearby allies.',
      },
    },
  },
  swordsman: {
    displayName: 'Swordsman',
    spriteKey: 'swordsman',
    unlockLevel: 0, // Unlocked by default
    baseStats: {
      health: 105,
      moveSpeed: 155,
      mana: 40,
      hpRecovery: 1,
      manaRecovery: 0.6,
      resistances: {
        sword: 15,
        axe: 0,
        bow: -5,
        spear: 0,
        dark: 0,
        spike: -5,
        claw: -5,
        greatsword: 10,
      },
    },
    attacks: sharedAttacks,
    passives: {
      passive1: {
        name: 'Sword Mastery',
        description:
          'Expert swordsmanship increases attack speed by +15% and parry chance by +10%.',
      },
    },
  },
};

// Export a default object for compatibility with existing imports
export default { jobs: jobAttributes };
