import type { JobConfig } from '@/player/combat/attack-types';

export const jobAttributes: Record<string, JobConfig> = {
  soldier: {
    displayName: 'Soldier',
    spriteKey: 'soldier',
    baseStats: {
      health: 100,
      moveSpeed: 160,
      mana: 30,
      hpRecovery: 1,
      manaRecovery: 0.5,
      resistances: {
        sword: 5,
        axe: 0,
        bow: -5,
        spear: -5,
        dark: 0,
        spike: -5,
        claw: -10,
        greatsword: 10,
      },
    },
    attacks: {
      attack1: {
        attackType: 'standard',
        name: 'Quick Strike',
        damage: 10,
        cooldown: 0,
        critChance: 0,
        knockback: 500,
        range: 50,
        hits: 1,
        targets: 5,
        modifiers: ['sword'],
        manaCost: 0,
        ammoCost: 0,
      },
      attack2: {
        attackType: 'standard',
        name: 'Power Slash',
        damage: 50,
        cooldown: 5,
        critChance: 0,
        knockback: 10,
        range: 75,
        hits: 1,
        targets: 6,
        modifiers: ['sword'],
        manaCost: 0,
        ammoCost: 0,
      },
      attack3: {
        attackType: 'standard',
        name: 'Combo Attack',
        damage: 15,
        cooldown: 0,
        critChance: 1,
        knockback: 8,
        range: 500,
        hits: 3,
        targets: 3,
        modifiers: ['sword'],
        manaCost: 5,
        ammoCost: 0,
      },
    },
    passives: {
      passive1: {
        name: 'Combat Training',
      },
    },
  },
  knight: {
    displayName: 'Knight',
    spriteKey: 'knight',
    baseStats: {
      health: 150,
      moveSpeed: 140,
      mana: 50,
      hpRecovery: 1.5,
      manaRecovery: 0.3,
      resistances: {
        sword: 20,
        axe: 15,
        bow: 5,
        spear: 10,
        dark: 10,
        spike: 15,
        claw: 10,
        greatsword: 25,
      },
    },
    attacks: {
      attack1: {
        attackType: 'standard',
        name: 'Sword Slash',
        damage: 12,
        cooldown: 350,
        critChance: 0.1,
        knockback: 5,
        range: 50,
        hits: 1,
        targets: 1,
        modifiers: ['sword'],
        manaCost: 0,
        ammoCost: 0,
      },
      attack2: {
        attackType: 'standard',
        name: 'Shield Bash',
        damage: 15,
        cooldown: 500,
        critChance: 0.05,
        knockback: 20,
        range: 40,
        hits: 1,
        targets: 1,
        modifiers: ['spike'],
        manaCost: 10,
        ammoCost: 0,
      },
      attack3: {
        attackType: 'standard',
        name: 'Heavy Cleave',
        damage: 25,
        cooldown: 800,
        critChance: 0.15,
        knockback: 15,
        range: 65,
        hits: 1,
        targets: 2,
        modifiers: ['sword'],
        manaCost: 15,
        ammoCost: 0,
      },
    },
    passives: {
      passive1: {
        name: 'Shield Wall',
      },
    },
  },
  wizard: {
    displayName: 'Wizard',
    spriteKey: 'wizard',
    baseStats: {
      health: 80,
      moveSpeed: 150,
      mana: 100,
      hpRecovery: 0.5,
      manaRecovery: 2,
      resistances: {
        sword: -10,
        axe: -10,
        bow: 0,
        spear: -5,
        dark: 20,
        spike: -15,
        claw: -15,
        greatsword: -5,
      },
    },
    attacks: {
      attack1: {
        attackType: 'projectile',
        name: 'Magic Missile',
        damage: 12,
        cooldown: 400,
        critChance: 0.2,
        knockback: 3,
        range: 400,
        hits: 1,
        targets: 1,
        modifiers: ['dark'],
        manaCost: 5,
        ammoCost: 0,
        projectileSpeed: 300,
        projectileSize: 10,
        projectileSprite: 'magicMissile',
      },
      attack2: {
        attackType: 'area',
        name: 'Arcane Blast',
        damage: 20,
        cooldown: 800,
        critChance: 0.25,
        knockback: 10,
        range: 80,
        hits: 1,
        targets: 3,
        modifiers: ['spike'],
        manaCost: 15,
        ammoCost: 0,
        radius: 80,
        effectSprite: 'arcaneBlast',
      },
      attack3: {
        attackType: 'area',
        name: 'Meteor Strike',
        damage: 30,
        cooldown: 1200,
        critChance: 0.1,
        knockback: 15,
        range: 120,
        hits: 3,
        targets: 5,
        modifiers: ['dark', 'spike'],
        manaCost: 25,
        ammoCost: 0,
        radius: 120,
        effectSprite: 'meteorStrike',
      },
    },
    passives: {
      passive1: {
        name: 'Arcane Power',
      },
    },
  },
  archer: {
    displayName: 'Archer',
    spriteKey: 'archer',
    baseStats: {
      health: 90,
      moveSpeed: 170,
      mana: 40,
      hpRecovery: 0.8,
      manaRecovery: 0.8,
      resistances: {
        sword: -5,
        axe: -5,
        bow: 15,
        spear: 0,
        dark: 5,
        spike: -10,
        claw: -10,
        greatsword: 0,
      },
    },
    attacks: {
      attack1: {
        attackType: 'projectile',
        name: 'Quick Shot',
        damage: 10,
        cooldown: 250,
        critChance: 0.25,
        knockback: 3,
        range: 500,
        hits: 1,
        targets: 1,
        modifiers: ['bow'],
        manaCost: 0,
        ammoCost: 1,
        projectileSpeed: 400,
        projectileSize: 8,
        projectileSprite: 'arrow',
      },
      attack2: {
        attackType: 'projectile',
        name: 'Power Shot',
        damage: 20,
        cooldown: 600,
        critChance: 0.35,
        knockback: 8,
        range: 600,
        hits: 1,
        targets: 1,
        modifiers: ['bow'],
        manaCost: 0,
        ammoCost: 1,
        projectileSpeed: 500,
        projectileSize: 10,
        projectileSprite: 'arrow',
      },
      attack3: {
        attackType: 'projectile',
        name: 'Multi Shot',
        damage: 12,
        cooldown: 800,
        critChance: 0.2,
        knockback: 5,
        range: 400,
        hits: 3,
        targets: 3,
        modifiers: ['bow'],
        manaCost: 5,
        ammoCost: 3,
        projectileSpeed: 350,
        projectileSize: 8,
        projectileSprite: 'arrow',
      },
    },
    passives: {
      passive1: {
        name: 'Eagle Eye',
      },
    },
  },
  armoredAxeman: {
    displayName: 'Armored Axeman',
    spriteKey: 'armored-axeman',
    baseStats: {
      health: 140,
      moveSpeed: 130,
      mana: 40,
      hpRecovery: 1.2,
      manaRecovery: 0.4,
      resistances: {
        sword: 10,
        axe: 25,
        bow: 0,
        spear: 5,
        dark: 0,
        spike: 10,
        claw: 5,
        greatsword: 20,
      },
    },
    attacks: {
      attack1: {
        attackType: 'standard',
        name: 'Axe Chop',
        damage: 14,
        cooldown: 400,
        critChance: 0.15,
        knockback: 6,
        range: 30,
        hits: 1,
        targets: 1,
        modifiers: ['axe'],
        manaCost: 0,
        ammoCost: 0,
      },
      attack2: {
        attackType: 'standard',
        name: 'Brutal Strike',
        damage: 22,
        cooldown: 700,
        critChance: 0.2,
        knockback: 12,
        range: 35,
        hits: 1,
        targets: 1,
        modifiers: ['axe'],
        manaCost: 0,
        ammoCost: 0,
      },
      attack3: {
        attackType: 'area',
        name: 'Whirlwind',
        damage: 18,
        cooldown: 1000,
        critChance: 0.1,
        knockback: 10,
        range: 60,
        hits: 2,
        targets: 4,
        modifiers: ['axe'],
        manaCost: 10,
        ammoCost: 0,
        radius: 60,
        effectSprite: 'whirlwind',
      },
    },
    passives: {
      passive1: {
        name: 'Heavy Armor',
      },
    },
  },
  knightTemplar: {
    displayName: 'Knight Templar',
    spriteKey: 'knight-templar',
    baseStats: {
      health: 160,
      moveSpeed: 135,
      mana: 80,
      hpRecovery: 2,
      manaRecovery: 1,
      resistances: {
        sword: 15,
        axe: 10,
        bow: 10,
        spear: 10,
        dark: -20,
        spike: 15,
        claw: 10,
        greatsword: 20,
      },
    },
    attacks: {
      attack1: {
        attackType: 'standard',
        name: 'Holy Strike',
        damage: 13,
        cooldown: 350,
        critChance: 0.12,
        knockback: 5,
        range: 45,
        hits: 1,
        targets: 1,
        modifiers: ['sword', 'greatsword'],
        manaCost: 0,
        ammoCost: 0,
      },
      attack2: {
        attackType: 'standard',
        name: 'Divine Smite',
        damage: 20,
        cooldown: 600,
        critChance: 0.15,
        knockback: 10,
        range: 50,
        hits: 1,
        targets: 2,
        modifiers: ['dark'],
        manaCost: 15,
        ammoCost: 0,
      },
      attack3: {
        attackType: 'area',
        name: 'Consecration',
        damage: 16,
        cooldown: 1200,
        critChance: 0.08,
        knockback: 8,
        range: 100,
        hits: 1,
        targets: 5,
        modifiers: ['dark', 'spike'],
        manaCost: 20,
        ammoCost: 0,
        radius: 100,
        effectSprite: 'consecration',
      },
    },
    passives: {
      passive1: {
        name: 'Divine Protection',
      },
    },
  },
  lancer: {
    displayName: 'Lancer',
    spriteKey: 'lancer',
    baseStats: {
      health: 110,
      moveSpeed: 165,
      mana: 50,
      hpRecovery: 1,
      manaRecovery: 0.7,
      resistances: {
        sword: 5,
        axe: 0,
        bow: -5,
        spear: 20,
        dark: 0,
        spike: -5,
        claw: -5,
        greatsword: 10,
      },
    },
    attacks: {
      attack1: {
        attackType: 'standard',
        name: 'Thrust',
        damage: 11,
        cooldown: 300,
        critChance: 0.18,
        knockback: 4,
        range: 70,
        hits: 1,
        targets: 1,
        modifiers: ['spear'],
        manaCost: 0,
        ammoCost: 0,
      },
      attack2: {
        attackType: 'standard',
        name: 'Piercing Strike',
        damage: 17,
        cooldown: 500,
        critChance: 0.22,
        knockback: 7,
        range: 80,
        hits: 1,
        targets: 2,
        modifiers: ['spear'],
        manaCost: 5,
        ammoCost: 0,
      },
      attack3: {
        attackType: 'standard',
        name: 'Dragon Dive',
        damage: 25,
        cooldown: 900,
        critChance: 0.3,
        knockback: 15,
        range: 100,
        hits: 1,
        targets: 3,
        modifiers: ['spear'],
        manaCost: 12,
        ammoCost: 0,
      },
    },
    passives: {
      passive1: {
        name: 'Reach Advantage',
      },
    },
  },
  priest: {
    displayName: 'Priest',
    spriteKey: 'priest',
    baseStats: {
      health: 85,
      moveSpeed: 145,
      mana: 120,
      hpRecovery: 1.5,
      manaRecovery: 2.5,
      resistances: {
        sword: -15,
        axe: -15,
        bow: -5,
        spear: -10,
        dark: -30,
        spike: -20,
        claw: -20,
        greatsword: -10,
      },
    },
    attacks: {
      attack1: {
        attackType: 'projectile',
        name: 'Dark Bolt',
        damage: 9,
        cooldown: 350,
        critChance: 0.15,
        knockback: 2,
        range: 350,
        hits: 1,
        targets: 1,
        modifiers: ['dark'],
        manaCost: 3,
        ammoCost: 0,
        projectileSpeed: 250,
        projectileSize: 12,
        projectileSprite: 'darkBolt',
      },
      attack2: {
        attackType: 'area',
        name: 'Shadow Burst',
        damage: 15,
        cooldown: 700,
        critChance: 0.18,
        knockback: 6,
        range: 70,
        hits: 1,
        targets: 3,
        modifiers: ['dark', 'spike'],
        manaCost: 12,
        ammoCost: 0,
        radius: 70,
        effectSprite: 'shadowBurst',
      },
      attack3: {
        attackType: 'area',
        name: 'Dark Wrath',
        damage: 22,
        cooldown: 1100,
        critChance: 0.12,
        knockback: 12,
        range: 90,
        hits: 2,
        targets: 4,
        modifiers: ['dark'],
        manaCost: 30,
        ammoCost: 0,
        radius: 90,
        effectSprite: 'darkWrath',
      },
    },
    passives: {
      passive1: {
        name: 'Blessed Recovery',
      },
    },
  },
  swordsman: {
    displayName: 'Swordsman',
    spriteKey: 'swordsman',
    baseStats: {
      health: 105,
      moveSpeed: 155,
      mana: 40,
      hpRecovery: 1,
      manaRecovery: 0.6,
      resistances: {
        sword: 15,
        axe: 0,
        bow: -5,
        spear: 0,
        dark: 0,
        spike: -5,
        claw: -5,
        greatsword: 10,
      },
    },
    attacks: {
      attack1: {
        attackType: 'standard',
        name: 'Slash',
        damage: 11,
        cooldown: 280,
        critChance: 0.2,
        knockback: 4,
        range: 35,
        hits: 1,
        targets: 1,
        modifiers: ['sword'],
        manaCost: 0,
        ammoCost: 0,
      },
      attack2: {
        attackType: 'standard',
        name: 'Double Slash',
        damage: 9,
        cooldown: 450,
        critChance: 0.18,
        knockback: 5,
        range: 40,
        hits: 2,
        targets: 2,
        modifiers: ['sword'],
        manaCost: 5,
        ammoCost: 0,
      },
      attack3: {
        attackType: 'standard',
        name: 'Blade Dance',
        damage: 14,
        cooldown: 750,
        critChance: 0.25,
        knockback: 8,
        range: 45,
        hits: 3,
        targets: 3,
        modifiers: ['sword'],
        manaCost: 10,
        ammoCost: 0,
      },
    },
    passives: {
      passive1: {
        name: 'Sword Mastery',
      },
    },
  },
};

// Export a default object for compatibility with existing imports
export default { jobs: jobAttributes };
