// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
// A namespace for generated variants and helper functions.
export namespace DamageType {
  // These are the generated variant types for each variant of the tagged union.
  // One type is generated per variant and will be used in the `value` field of
  // the tagged union.
  export type Weak = { tag: "Weak" };
  export type Strong = { tag: "Strong" };
  export type Crit = { tag: "Crit" };
  export type Normal = { tag: "Normal" };
  export type Immune = { tag: "Immune" };

  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  export const Weak = { tag: "Weak" };
  export const Strong = { tag: "Strong" };
  export const Crit = { tag: "Crit" };
  export const Normal = { tag: "Normal" };
  export const Immune = { tag: "Immune" };

  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createSumType([
      new SumTypeVariant("Weak", AlgebraicType.createProductType([])),
      new SumTypeVariant("Strong", AlgebraicType.createProductType([])),
      new SumTypeVariant("Crit", AlgebraicType.createProductType([])),
      new SumTypeVariant("Normal", AlgebraicType.createProductType([])),
      new SumTypeVariant("Immune", AlgebraicType.createProductType([])),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: DamageType): void {
      DamageType.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): DamageType {
      return DamageType.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

// The tagged union or sum type for the algebraic type `DamageType`.
export type DamageType = DamageType.Weak | DamageType.Strong | DamageType.Crit | DamageType.Normal | DamageType.Immune;

export default DamageType;

