// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { PartyMember } from "./party_member_type";
import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `PartyMember`.
 *
 * Obtain a handle from the [`partyMember`] property on [`RemoteTables`],
 * like `ctx.db.partyMember`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.partyMember.on_insert(...)`.
 */
export class PartyMemberTableHandle {
  tableCache: TableCache<PartyMember>;

  constructor(tableCache: TableCache<PartyMember>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<PartyMember> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `partyMemberId` unique index on the table `PartyMember`,
   * which allows point queries on the field of the same name
   * via the [`PartyMemberPartyMemberIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.partyMember.partyMemberId().find(...)`.
   *
   * Get a handle on the `partyMemberId` unique index on the table `PartyMember`.
   */
  partyMemberId = {
    // Find the subscribed row whose `partyMemberId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): PartyMember | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.partyMemberId, col_val)) {
          return row;
        }
      }
    },
  };
  /**
   * Access to the `playerIdentity` unique index on the table `PartyMember`,
   * which allows point queries on the field of the same name
   * via the [`PartyMemberPlayerIdentityUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.partyMember.playerIdentity().find(...)`.
   *
   * Get a handle on the `playerIdentity` unique index on the table `PartyMember`.
   */
  playerIdentity = {
    // Find the subscribed row whose `playerIdentity` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: Identity): PartyMember | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.playerIdentity, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: PartyMember) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: PartyMember) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: PartyMember) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: PartyMember) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: PartyMember, newRow: PartyMember) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: PartyMember, newRow: PartyMember) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
