// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { FacingDirection as __FacingDirection } from "./facing_direction_type";
import { PlayerState as __PlayerState } from "./player_state_type";

export type Spawn = {
  spawnId: number,
  routeId: number,
  enemy: string,
  x: number,
  y: number,
  state: __PlayerState,
  facing: __FacingDirection,
  currentHp: number,
  level: number,
  lastUpdated: Timestamp,
  movingRight: boolean,
  aggroTarget: Identity | undefined,
  aggroStartTime: Timestamp,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Spawn {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("spawnId", AlgebraicType.createU32Type()),
      new ProductTypeElement("routeId", AlgebraicType.createU32Type()),
      new ProductTypeElement("enemy", AlgebraicType.createStringType()),
      new ProductTypeElement("x", AlgebraicType.createF32Type()),
      new ProductTypeElement("y", AlgebraicType.createF32Type()),
      new ProductTypeElement("state", __PlayerState.getTypeScriptAlgebraicType()),
      new ProductTypeElement("facing", __FacingDirection.getTypeScriptAlgebraicType()),
      new ProductTypeElement("currentHp", AlgebraicType.createF32Type()),
      new ProductTypeElement("level", AlgebraicType.createU32Type()),
      new ProductTypeElement("lastUpdated", AlgebraicType.createTimestampType()),
      new ProductTypeElement("movingRight", AlgebraicType.createBoolType()),
      new ProductTypeElement("aggroTarget", AlgebraicType.createOptionType(AlgebraicType.createIdentityType())),
      new ProductTypeElement("aggroStartTime", AlgebraicType.createTimestampType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Spawn): void {
    Spawn.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Spawn {
    return Spawn.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


