// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";

// Import and reexport all reducer arg types
import { CleanupInactivePlayers } from "./cleanup_inactive_players_reducer.ts";
export { CleanupInactivePlayers };
import { Connect } from "./connect_reducer.ts";
export { Connect };
import { Debug } from "./debug_reducer.ts";
export { Debug };
import { Disconnect } from "./disconnect_reducer.ts";
export { Disconnect };
import { UpdatePlayerPosition } from "./update_player_position_reducer.ts";
export { UpdatePlayerPosition };

// Import and reexport all table handle types
import { PlayerTableHandle } from "./player_table.ts";
export { PlayerTableHandle };

// Import and reexport all types
import { DbVector2 } from "./db_vector_2_type.ts";
export { DbVector2 };
import { Player } from "./player_type.ts";
export { Player };

const REMOTE_MODULE = {
  tables: {
    player: {
      tableName: "player",
      rowType: Player.getTypeScriptAlgebraicType(),
      primaryKey: "identity",
      primaryKeyInfo: {
        colName: "identity",
        colType: Player.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
  },
  reducers: {
    CleanupInactivePlayers: {
      reducerName: "CleanupInactivePlayers",
      argsType: CleanupInactivePlayers.getTypeScriptAlgebraicType(),
    },
    Connect: {
      reducerName: "Connect",
      argsType: Connect.getTypeScriptAlgebraicType(),
    },
    Debug: {
      reducerName: "Debug",
      argsType: Debug.getTypeScriptAlgebraicType(),
    },
    Disconnect: {
      reducerName: "Disconnect",
      argsType: Disconnect.getTypeScriptAlgebraicType(),
    },
    UpdatePlayerPosition: {
      reducerName: "UpdatePlayerPosition",
      argsType: UpdatePlayerPosition.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.2.0",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: DbConnectionImpl, event: Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "CleanupInactivePlayers", args: CleanupInactivePlayers }
| { name: "Connect", args: Connect }
| { name: "Debug", args: Debug }
| { name: "Disconnect", args: Disconnect }
| { name: "UpdatePlayerPosition", args: UpdatePlayerPosition }
;

export class RemoteReducers {
  constructor(private connection: DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  cleanupInactivePlayers() {
    this.connection.callReducer("CleanupInactivePlayers", new Uint8Array(0), this.setCallReducerFlags.cleanupInactivePlayersFlags);
  }

  onCleanupInactivePlayers(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("CleanupInactivePlayers", callback);
  }

  removeOnCleanupInactivePlayers(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("CleanupInactivePlayers", callback);
  }

  onConnect(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("Connect", callback);
  }

  removeOnConnect(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("Connect", callback);
  }

  debug() {
    this.connection.callReducer("Debug", new Uint8Array(0), this.setCallReducerFlags.debugFlags);
  }

  onDebug(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("Debug", callback);
  }

  removeOnDebug(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("Debug", callback);
  }

  onDisconnect(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("Disconnect", callback);
  }

  removeOnDisconnect(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("Disconnect", callback);
  }

  updatePlayerPosition(x: number, y: number) {
    const __args = { x, y };
    let __writer = new BinaryWriter(1024);
    UpdatePlayerPosition.getTypeScriptAlgebraicType().serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("UpdatePlayerPosition", __argsBuffer, this.setCallReducerFlags.updatePlayerPositionFlags);
  }

  onUpdatePlayerPosition(callback: (ctx: ReducerEventContext, x: number, y: number) => void) {
    this.connection.onReducer("UpdatePlayerPosition", callback);
  }

  removeOnUpdatePlayerPosition(callback: (ctx: ReducerEventContext, x: number, y: number) => void) {
    this.connection.offReducer("UpdatePlayerPosition", callback);
  }

}

export class SetReducerFlags {
  cleanupInactivePlayersFlags: CallReducerFlags = 'FullUpdate';
  cleanupInactivePlayers(flags: CallReducerFlags) {
    this.cleanupInactivePlayersFlags = flags;
  }

  debugFlags: CallReducerFlags = 'FullUpdate';
  debug(flags: CallReducerFlags) {
    this.debugFlags = flags;
  }

  updatePlayerPositionFlags: CallReducerFlags = 'FullUpdate';
  updatePlayerPosition(flags: CallReducerFlags) {
    this.updatePlayerPositionFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: DbConnectionImpl) {}

  get player(): PlayerTableHandle {
    return new PlayerTableHandle(this.connection.clientCache.getOrCreateTable<Player>(REMOTE_MODULE.tables.player));
  }
}

export class SubscriptionBuilder extends SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
